### POST "fnfunfunc"
POST http://localhost:8080/manage/create-admin
Content-Type: application/json

{
  "account": "fnfunfunc",
  "password": "1234"
}

### Login "fnfunfunc"
POST http://localhost:8080/admin/login
Content-Type: application/json

{
  "account": "fnfunfunc",
  "password": "1234"
}

### Register Company "联小创在线科技有限公司"
POST http://localhost:8080/company/register
Content-Type: application/json

{
  "account": "联创",
  "password": "uniquestudio",
  "name": "联小创在线科技有限公司",
  "address": "启明学院亮胜楼八楼",
  "manager_name": "汉堡",
  "manager_tel": "1919810",
  "business_license_number": "114514"
}

### Login Company "联小创在线科技有限公司"
POST http://localhost:8080/company/login
Content-Type: application/json

{
  "account": "联创",
  "password": "uniquestudio"
}

### List pending review companies
GET http://localhost:8080/manage/company/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZuZnVuZnVuYyIsInBhc3N3b3JkIjoiJDJhJDEwJGZ3UVBVbDRGZkZRVDBIUXE5QzNremVVNTc1OGdNMW5VdTguZTRCcXphTnprOG9Hb3VwOUptIiwiTWFwQ2xhaW1zIjp7ImV4cCI6MTY4MjE4NjY5MDI5Miwicm9sZSI6InJvbGVfYWRtaW4ifX0.g5xSTvmZKN5ViwgmHMAtRoqu57HTHFMBYrFQmggRC4o

### List all registered companies
GET http://localhost:8080/manage/company/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZuZnVuZnVuYyIsInBhc3N3b3JkIjoiJDJhJDEwJGZ3UVBVbDRGZkZRVDBIUXE5QzNremVVNTc1OGdNMW5VdTguZTRCcXphTnprOG9Hb3VwOUptIiwiTWFwQ2xhaW1zIjp7ImV4cCI6MTY4MjE4NjY5MDI5Miwicm9sZSI6InJvbGVfYWRtaW4ifX0.g5xSTvmZKN5ViwgmHMAtRoqu57HTHFMBYrFQmggRC4o


### Allow "联小创在线科技有限公司"
POST http://localhost:8080/manage/company/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZuZnVuZnVuYyIsInBhc3N3b3JkIjoiJDJhJDEwJGZ3UVBVbDRGZkZRVDBIUXE5QzNremVVNTc1OGdNMW5VdTguZTRCcXphTnprOG9Hb3VwOUptIiwiTWFwQ2xhaW1zIjp7ImV4cCI6MTY4MjE4NjY5MDI5Miwicm9sZSI6InJvbGVfYWRtaW4ifX0.g5xSTvmZKN5ViwgmHMAtRoqu57HTHFMBYrFQmggRC4o
Content-Type: application/json

{
  "company_accounts": ["联创"]
}

### Search "联小创在线科技有限公司"
GET http://localhost:8080/manage/company/search?term=联小创在线科技有限公司&type=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZuZnVuZnVuYyIsInBhc3N3b3JkIjoiJDJhJDEwJGZ3UVBVbDRGZkZRVDBIUXE5QzNremVVNTc1OGdNMW5VdTguZTRCcXphTnprOG9Hb3VwOUptIiwiTWFwQ2xhaW1zIjp7ImV4cCI6MTY4MjE4NjY5MDI5Miwicm9sZSI6InJvbGVfYWRtaW4ifX0.g5xSTvmZKN5ViwgmHMAtRoqu57HTHFMBYrFQmggRC4o
